### PR TITLE
add few information about ducc

### PR DESCRIPTION
**Pull request by siscia**
Adding few information about the latest development of DUCC

### CODE REVIEW

**Comment by rptaylor** [comment]
Is this a work in progress , or ready to merge?

**Comment by siscia** [comment]
Hi Ryan,

it is  a pleasure to hear from you! I hope everything is good from your side!

If I recall correctly, the features documented are already in the DUCC code, please don't quote me on this and check for yourself, I lost track of the latest developments.

However, I don't  work anymore at CERN and in the project, so I cannot merge the request, and I believe it is more correct that the current CVMFS team decides what to include in the documentation.

Anyway the documented features were used in pre-production, and for the short time I used them were rather ok.

Cheers,
Simone

**Comment by rptaylor** [comment]
@siscia  thanks hope you're doing well too! I didn't know you left CERN, good luck in your new endeavours!

Okay thanks for the update, hopefully the docs can be merged if/when ready by a current team member.

**Comment by jblomer** [comment]
Sure! Sorry about the delay, it's ready and I simply overlooked to merge.

**Pull request merged**
