### PR TITLE
Some more info on how to build software for cvmfs

### PR DESCRIPTION
**Pull request by siscia**
I would like to expand more this chapter, but I believe it is a good start.

### CODE REVIEW

**Comment by DrDaveD** [comment]
This is one way to do it, and I think at least the intro should make that clear.  It seems to me to be a pretty complex way for a user.   Isn't it easier to use singularity --writable?

**Comment by rptaylor** [comment]
@jblomer   @siscia   perhaps this one is mergeable too?

**Comment by jblomer** [comment]
This one needs one more round of contemplation from my side.  I agree with Dave that such a chapter, if it's not very clear, can confuse rather than help.

**Comment by DrDaveD** [comment]
I think the process is too complicated to be a document.  If this is needed, there should be a tool that makes it easy.

**Pull request closed without merging**
